# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-31 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('footer', models.TextField(blank=True, default='')),
            ],
        ),
    ]
